field: 8fea7832-8658-4760-82a2-fea191ae7ac0 # Blocks
fieldLayouts:
  cc28fe65-95e9-486d-83d5-b4a562f67d58:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 4117a0d7-1077-4b6b-aee2-49fe2f067165 # photos
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 966e2939-f0e5-4be5-84e2-90ca1b2b569e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 90c8f29a-0a89-4d30-b3aa-d06a90af4d85
        userCondition: null
fields:
  4117a0d7-1077-4b6b-aee2-49fe2f067165: # photos
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: photos
    instructions: null
    name: photos
    searchable: false
    settings:
      blockTypeFields: 0
      changedFieldIndicator: 591432741
      columns:
        __assoc__:
          -
            - 8a94f6f0-17f0-45ff-bcab-aba52fa8a6e8 # photo
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_9_photos}}'
      fieldLayout: table
      maxRows: null
      minRows: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: null
      staticField: null
    translationKeyFormat: null
    translationMethod: none
    type: verbb\supertable\fields\SuperTableField
handle: photoGallery
name: 'Photo Gallery'
sortOrder: 6
