field: 8fea7832-8658-4760-82a2-fea191ae7ac0 # Blocks
fieldLayouts:
  c9f740fa-fe7c-4524-ba68-5db333bbc3e0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 1782a7b8-9a4c-46f5-a0b7-2588b902cf4b # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b324bab8-3ac3-4b53-ba61-29b6ba2a3437
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3cb37d07-55f6-4ffd-aaf4-b7b4e763c53c # Logos
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2c6cb469-60d8-475b-b518-45ea57987f0b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2f6722f7-e447-40db-b488-ab47620851dc
        userCondition: null
fields:
  3cb37d07-55f6-4ffd-aaf4-b7b4e763c53c: # Logos
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: logos
    instructions: null
    name: Logos
    searchable: false
    settings:
      blockTypeFields: 0
      changedFieldIndicator: 1929585602
      columns:
        __assoc__:
          -
            - d3107f36-78e5-4715-b75f-8e03700aaf81 # Logo
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - d4f26e3f-b377-4e05-b84c-dbf98e64f826 # Link
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_7_logos}}'
      fieldLayout: row
      maxRows: null
      minRows: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: 'Add a logo'
      staticField: null
    translationKeyFormat: null
    translationMethod: none
    type: verbb\supertable\fields\SuperTableField
  1782a7b8-9a4c-46f5-a0b7-2588b902cf4b: # Heading
    columnSuffix: ljtesozj
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: null
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: sponsorLogoGroup
name: 'Sponsor Logo Group'
sortOrder: 5
