field: 8fea7832-8658-4760-82a2-fea191ae7ac0 # Blocks
fieldLayouts:
  6d6378eb-a26c-40da-be7b-8d6606f0d285:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: ea4cc075-2720-4b5e-8764-d87555c1ba68 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3bbc7599-5783-4771-ab01-77a7eca099f2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0e32b2e3-7176-4e6b-b27a-a9d009520a89 # Events
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 595db118-cd74-49a1-9746-c9c3e1bc1bab
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9772b8b7-0ed3-43b2-a223-699c645fdf2b
        userCondition: null
fields:
  0e32b2e3-7176-4e6b-b27a-a9d009520a89: # Events
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: events
    instructions: null
    name: Events
    searchable: false
    settings:
      blockTypeFields: 0
      changedFieldIndicator: 1180622607
      columns:
        __assoc__:
          -
            - e0a28370-0059-4791-9624-2383f68b6460 # Heading
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 736cdbf1-41f2-49c9-9d94-9599ac7f26d3 # Image
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 4a8f835f-f041-427c-a837-acc1f3a8c973 # Text
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_8_events}}'
      fieldLayout: row
      maxRows: null
      minRows: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: 'Add event'
      staticField: null
    translationKeyFormat: null
    translationMethod: none
    type: verbb\supertable\fields\SuperTableField
  ea4cc075-2720-4b5e-8764-d87555c1ba68: # Heading
    columnSuffix: aydlsfcu
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: 'Give the timeline a title heading here!'
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: timeline
name: Timeline
sortOrder: 4
