dateModified: 1681860728
email:
  fromEmail: me@levizitting.com
  fromName: 'The Invisible Man Leadership Program'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  public:
    hasUrls: true
    name: Public
    settings:
      path: '@webroot/assets'
    type: craft\fs\Local
    url: '@web/assets'
meta:
  __names__:
    1f8ded3d-464f-4677-a20e-a7a8ace195b3: Image # Image
    3d5f9f28-5e41-424d-9e51-8c6791fe0561: 'Public Assets' # Public Assets
    3e6f485a-bd73-4877-a29e-329994951ea5: Cards # Cards
    5ee7c67e-32cf-4b9c-b3fe-a14f86f2f60c: Title # Title
    6b6afd05-9cc6-4a8b-a9b0-426ae2ec21c5: 'Stats Table' # Stats Table
    7dd82277-b22c-4d92-993d-429ae8f92bf8: Common # Common
    8fea7832-8658-4760-82a2-fea191ae7ac0: Blocks # Blocks
    16c32343-c234-4479-a53b-8de7cad7cf71: 'The Invisible Man Leadership Program' # The Invisible Man Leadership Program
    33b3fe32-761b-491c-bd8d-bbd1ee0e320a: Text # Text
    55fa79ea-5553-42d9-8e46-93726cd9c7e3: Heading # Heading
    89c63208-2f9e-4fb3-9562-c5c4a709733f: Title # Title
    598a041c-a952-43d7-8130-a659fcddd233: Stats # Stats
    665f6825-9a80-4138-a2bf-847c424ec67b: 'Stat Item' # Stat Item
    698fb72b-9d3b-499e-a0c9-63bb555150b8: Description # Description
    1467d9bb-2f87-4770-aa6e-91b0edc0353b: 'The Invisible Man Leadership Program' # The Invisible Man Leadership Program
    5335c937-f52e-46bc-b450-ce1c783b5042: Title # Title
    7593fe81-7596-4faa-bef4-aac9d25d34e2: Hero # Hero
    59727c02-1fb5-44ba-97e1-7750af27abd4: 'Card Set' # Card Set
    a346e097-745f-4395-a326-411a4ff70c9d: 'Callout Link' # Callout Link
    b7cfb2f9-efc2-4e6f-b8a8-3d28d9d92e2f: Home # Home
    b54fd2e5-a591-4b7e-b183-a34f283cc000: Heading # Heading
    c9ad660a-b24e-4c3d-b87f-685185cc32f2: 'Background Image' # Background Image
    d5a81be2-83ca-46a2-a9d4-d97d68b8da6f: Home # Home
    e4c794ce-2250-48f7-86fe-cc451727b17f: 'Rich Text' # Rich Text
    e4f4af5c-69d6-4acc-9fc4-c70666b6c415: Simple # Simple
    f2206ae6-9a42-4b03-b6fd-c88253dff38c: 'Example Input' # Example Input
    f9911ada-d8f1-439c-a699-315a06fc42f8: 'Sub Heading' # Sub Heading
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  super-table:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0
  typedlinkfield:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: 'The Invisible Man Leadership Program'
  schemaVersion: 4.4.0.4
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
