changedFieldIndicator: 1297318351
field: 3cb37d07-55f6-4ffd-aaf4-b7b4e763c53c # Logos
fieldLayouts:
  d8a36691-2861-4c39-aa86-7674bcc927d1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: d3107f36-78e5-4715-b75f-8e03700aaf81 # Logo
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 12234d98-e727-43aa-a4b1-b3a5631ec241
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d4f26e3f-b377-4e05-b84c-dbf98e64f826 # Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 75a51b37-8917-4ab6-a800-16d055dce60e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 545a2159-d005-4b76-b4a7-c05076e83089
        userCondition: null
fields:
  d4f26e3f-b377-4e05-b84c-dbf98e64f826: # Link
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: customLink
    instructions: null
    name: Link
    searchable: false
    settings:
      allowCustomText: false
      allowTarget: true
      autoNoReferrer: true
      customTextMaxLength: 0
      customTextRequired: false
      defaultLinkName: entry
      defaultText: ''
      enableAllLinkTypes: true
      enableAriaLabel: false
      enableElementCache: false
      enableTitle: true
      typeSettings:
        asset:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        category:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        custom:
          allowAliases: false
          disableValidation: false
          enabled: false
        email:
          allowAliases: false
          disableValidation: false
          enabled: false
        entry:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        site:
          enabled: false
          sites: '*'
        tel:
          allowAliases: false
          disableValidation: false
          enabled: false
        url:
          allowAliases: false
          disableValidation: false
          enabled: false
        user:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
    translationKeyFormat: null
    translationMethod: none
    type: lenz\linkfield\fields\LinkField
  d3107f36-78e5-4715-b75f-8e03700aaf81: # Logo
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: logo
    instructions: null
    name: Logo
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:3d5f9f28-5e41-424d-9e51-8c6791fe0561' # Public Assets
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:3d5f9f28-5e41-424d-9e51-8c6791fe0561' # Public Assets
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
