changedFieldIndicator: 1064993978
field: 0e32b2e3-7176-4e6b-b27a-a9d009520a89 # Events
fieldLayouts:
  365eadaf-c091-4d33-8a18-c80041211023:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e0a28370-0059-4791-9624-2383f68b6460 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2d80226a-a29b-4a0d-bece-fad1b412a7e6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 736cdbf1-41f2-49c9-9d94-9599ac7f26d3 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7c99d9ff-ad62-46d3-bcb5-6e809dbc51f7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4a8f835f-f041-427c-a837-acc1f3a8c973 # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8d4f91d4-de80-43e0-a25f-88f72f700633
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 83fdee6a-a9b4-43af-86d1-40fdb25f17b3
        userCondition: null
fields:
  4a8f835f-f041-427c-a837-acc1f3a8c973: # Text
    columnSuffix: jfrozfkw
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: 'A few sentences to describe this part of the story, under the Timeline Event Heading'
    name: Text
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      ckeConfig: e4f4af5c-69d6-4acc-9fc4-c70666b6c415 # Simple
      columnType: text
      defaultTransform: null
      purifierConfig: null
      purifyHtml: true
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
  736cdbf1-41f2-49c9-9d94-9599ac7f26d3: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: 'A picture of or at least related to the timeline Event'
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:3d5f9f28-5e41-424d-9e51-8c6791fe0561' # Public Assets
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:3d5f9f28-5e41-424d-9e51-8c6791fe0561' # Public Assets
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  e0a28370-0059-4791-9624-2383f68b6460: # Heading
    columnSuffix: udxsloes
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: 'A summary statement of a significant event in the story. '
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
