changedFieldIndicator: 1680406722
changedFieldIndicator: 1014086447
field: 3e6f485a-bd73-4877-a29e-329994951ea5 # Cards
fieldLayouts:
  c858d43e-0b31-4d24-a10f-bfb286306568:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 1f8ded3d-464f-4677-a20e-a7a8ace195b3 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4c5490da-a8d5-40d3-b7e9-05a7579f0a08
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 55fa79ea-5553-42d9-8e46-93726cd9c7e3 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 77337e15-3eb8-46ba-b680-32384479b5fd
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f9911ada-d8f1-439c-a699-315a06fc42f8 # Sub Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ecc87d32-3ef8-408b-930c-04bcdc5e39d2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 698fb72b-9d3b-499e-a0c9-63bb555150b8 # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: db0d3355-4f08-43d9-bdcb-d1ddbbf4391f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3bd775ba-9b66-44a2-b5f1-cf794acf1ee0
        userCondition: null
fields:
  1f8ded3d-464f-4677-a20e-a7a8ace195b3: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      branchLimit: null
      defaultUploadLocationSource: 'volume:3d5f9f28-5e41-424d-9e51-8c6791fe0561' # Public Assets
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:3d5f9f28-5e41-424d-9e51-8c6791fe0561' # Public Assets
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  55fa79ea-5553-42d9-8e46-93726cd9c7e3: # Heading
    columnSuffix: gczbkkny
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: null
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  698fb72b-9d3b-499e-a0c9-63bb555150b8: # Description
    columnSuffix: qfwohqrj
    contentColumnType: text
    fieldGroup: null
    handle: description
    instructions: null
    name: Description
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  f9911ada-d8f1-439c-a699-315a06fc42f8: # Sub Heading
    columnSuffix: hsmikpap
    contentColumnType: text
    fieldGroup: null
    handle: subHeading
    instructions: null
    name: 'Sub Heading'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
