changedFieldIndicator: 1864631495
field: dbe1bd8a-c52b-418f-be3b-fe46ac093d9c # Tabs
fieldLayouts:
  f3960fc8-3cf6-4ddc-907c-fb89dd8ee7ef:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 236f1e3d-b5b7-48b9-9407-f06fa45d0d13 # Tab Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a3aaadfb-207e-431d-ab05-f9f9abf42a23
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3807ab11-9fdf-49ac-9af0-9ca3e77892fd # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4628ab7d-248c-48d3-9f59-d76d96fec5d2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 12ea636b-5a1f-4623-987d-16d5a681feb6 # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 62574cf4-6930-428d-bec9-3453911a3f95
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d28b8567-1d40-4d40-8f1b-3208f4063d3b # Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dbed3cff-2d00-420b-97de-b0ac2bf6e8ef
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d327aaf4-e24c-481c-9c6a-4ee998f4beef
        userCondition: null
fields:
  12ea636b-5a1f-4623-987d-16d5a681feb6: # Text
    columnSuffix: gnnthnms
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Text
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      ckeConfig: e4f4af5c-69d6-4acc-9fc4-c70666b6c415 # Simple
      columnType: text
      defaultTransform: null
      purifierConfig: null
      purifyHtml: true
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
  236f1e3d-b5b7-48b9-9407-f06fa45d0d13: # Tab Title
    columnSuffix: cwkmmfdc
    contentColumnType: text
    fieldGroup: null
    handle: tabTitle
    instructions: null
    name: 'Tab Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  3807ab11-9fdf-49ac-9af0-9ca3e77892fd: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:3d5f9f28-5e41-424d-9e51-8c6791fe0561' # Public Assets
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:3d5f9f28-5e41-424d-9e51-8c6791fe0561' # Public Assets
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  d28b8567-1d40-4d40-8f1b-3208f4063d3b: # Link
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: customLink
    instructions: null
    name: Link
    searchable: false
    settings:
      allowCustomText: true
      allowTarget: true
      autoNoReferrer: true
      customTextMaxLength: 0
      customTextRequired: true
      defaultLinkName: entry
      defaultText: ''
      enableAllLinkTypes: true
      enableAriaLabel: false
      enableElementCache: false
      enableTitle: true
      typeSettings:
        asset:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        category:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        custom:
          allowAliases: false
          disableValidation: false
          enabled: false
        email:
          allowAliases: false
          disableValidation: false
          enabled: false
        entry:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        site:
          enabled: false
          sites: '*'
        tel:
          allowAliases: false
          disableValidation: false
          enabled: false
        url:
          allowAliases: false
          disableValidation: false
          enabled: false
        user:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
    translationKeyFormat: null
    translationMethod: none
    type: lenz\linkfield\fields\LinkField
