changedFieldIndicator: 1689943681
field: 0860b495-70e4-4cb4-87fa-049ae655ddc9 # Hero
fieldLayouts:
  8d901d98-c722-4cee-9ade-b4dec3fece53:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: b14585f2-af69-49dd-af4c-8866c1976ec8 # Heading
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7eab1df3-c827-42fa-9609-adcdaf104411
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4484d532-0100-495e-ac29-1e08c80ef497 # Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2dc5668e-039c-49a3-82f0-822ed1c28f32
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 235be42c-89e7-4ee3-9ee1-dfb27163a43e # Images
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aa572bbe-8af7-4eb4-a567-4dc6c5f95820
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6556c14b-43e7-4cb0-a500-7bb2a2c85b4d
        userCondition: null
fields:
  235be42c-89e7-4ee3-9ee1-dfb27163a43e: # Images
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: images
    instructions: null
    name: Images
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:3d5f9f28-5e41-424d-9e51-8c6791fe0561' # Public Assets
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 4
      minRelations: 4
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:3d5f9f28-5e41-424d-9e51-8c6791fe0561' # Public Assets
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  4484d532-0100-495e-ac29-1e08c80ef497: # Link
    columnSuffix: afsgqkrc
    contentColumnType: string
    fieldGroup: null
    handle: customLink
    instructions: null
    name: Link
    searchable: false
    settings:
      allowCustomText: true
      allowTarget: true
      autoNoReferrer: true
      customTextMaxLength: 0
      customTextRequired: true
      defaultLinkName: entry
      defaultText: ''
      enableAllLinkTypes: true
      enableAriaLabel: false
      enableElementCache: false
      enableTitle: true
      typeSettings:
        asset:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        category:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        custom:
          allowAliases: false
          disableValidation: false
          enabled: false
        email:
          allowAliases: false
          disableValidation: false
          enabled: false
        entry:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        site:
          enabled: false
          sites: '*'
        tel:
          allowAliases: false
          disableValidation: false
          enabled: false
        url:
          allowAliases: false
          disableValidation: false
          enabled: false
        user:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
    translationKeyFormat: null
    translationMethod: none
    type: lenz\linkfield\fields\LinkField
  b14585f2-af69-49dd-af4c-8866c1976ec8: # Heading
    columnSuffix: ilyopvpw
    contentColumnType: string(255)
    fieldGroup: null
    handle: heading
    instructions: null
    name: Heading
    searchable: false
    settings:
      maxLength: 255
      types:
        - url
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
