changedFieldIndicator: 333829259
field: 4117a0d7-1077-4b6b-aee2-49fe2f067165 # photos
fieldLayouts:
  0942eae7-8b56-4ede-9e83-39c9823933c5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 8a94f6f0-17f0-45ff-bcab-aba52fa8a6e8 # photo
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6f54cec5-25ff-4033-8982-d5d9d5317a99
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: dc9dd281-2e5a-4168-ac16-cefd44b07e74
        userCondition: null
fields:
  8a94f6f0-17f0-45ff-bcab-aba52fa8a6e8: # photo
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: photo
    instructions: null
    name: photo
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:3d5f9f28-5e41-424d-9e51-8c6791fe0561' # Public Assets
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:3d5f9f28-5e41-424d-9e51-8c6791fe0561' # Public Assets
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
